### ISSUE TITLE
Create API for students

### ISSUE THREAD

**Issue by nickdotreid** [presnick/RunestoneServer#50]
I wanted to log this idea before it completely slipped my/Jackie's mind(s).

We were thinking it would be fun for students to allow them access to their own db.useinfo data, which we would return in JSON format.

I know we are planning to wrap this into a visualization on a student's progress page, but I thought this might be a fun secondary use to allow.

Please add thoughts below.

**Comment by aerenchyma** [comment]
Would like to come back to this. Now, with more experience on the Jackie end of things...
